import {
  FaBoxes,
  FaBullhorn,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaClipboard,
  FaCogs,
  FaComments,
  FaDolly,
  FaFlask,
  FaGavel,
  FaGraduationCap,
  FaHeadset,
  FaHeartbeat,
  FaIndustry,
  FaLaptopCode,
  FaMoneyBillWave,
  FaPaintBrush,
  FaTruck,
  FaUserFriends,
} from "react-icons/fa";
export const jobDepartments = [
  { label: "Information Technology (IT)", icon: FaLaptopCode, value: "it" },
  { label: "Human Resources (HR)", icon: FaUserFriends, value: "hr" },
  { label: "Sales and Marketing", icon: FaChartLine, value: "sales_marketing" },
  {
    label: "Finance and Accounting",
    icon: FaMoneyBillWave,
    value: "finance_accounting",
  },
  { label: "Customer Service", icon: FaHeadset, value: "customer_service" },
  {
    label: "Operations and Logistics",
    icon: FaTruck,
    value: "operations_logistics",
  },
  { label: "Research and Development (R&D)", icon: FaFlask, value: "rnd" },
  { label: "Engineering", icon: FaCogs, value: "engineering" },
  { label: "Product Management", icon: FaBoxes, value: "product_management" },
  { label: "Administration", icon: FaClipboard, value: "administration" },
  { label: "Legal", icon: FaGavel, value: "legal" },
  { label: "Healthcare", icon: FaHeartbeat, value: "healthcare" },
  {
    label: "Design and Creative",
    icon: FaPaintBrush,
    value: "design_creative",
  },
  {
    label: "Education and Training",
    icon: FaGraduationCap,
    value: "education_training",
  },
  { label: "Manufacturing", icon: FaIndustry, value: "manufacturing" },
  { label: "Consulting", icon: FaComments, value: "consulting" },
  { label: "Supply Chain Management", icon: FaDolly, value: "supply_chain" },
  { label: "Public Relations (PR)", icon: FaBullhorn, value: "pr" },
  {
    label: "Business Development",
    icon: FaChartBar,
    value: "business_development",
  },
  {
    label: "Data Science and Analytics",
    icon: FaChartPie,
    value: "data_science_analytics",
  },
];

export const frameworks = [
  { value: "communication", label: "Communication Skills" },
  { value: "negotiation", label: "Negotiation Skills" },
  { value: "customer_service", label: "Customer Service" },
  { value: "digital_marketing", label: "Digital Marketing" },
  { value: "market_analysis", label: "Market Analysis" },
  { value: "javascript", label: "JavaScript" },
  { value: "react", label: "React" },
  { value: "node_js", label: "Node.js" },
  { value: "css", label: "CSS" },
  { value: "git", label: "Git" },
  { value: "recruitment", label: "Recruitment" },
  { value: "employee_relations", label: "Employee Relations" },
  { value: "performance_management", label: "Performance Management" },
  { value: "payroll_management", label: "Payroll Management" },
  { value: "conflict_resolution", label: "Conflict Resolution" },
  { value: "financial_analysis", label: "Financial Analysis" },
  { value: "accounting", label: "Accounting" },
  { value: "budgeting", label: "Budgeting" },
  { value: "investment_analysis", label: "Investment Analysis" },
  { value: "taxation", label: "Taxation" },
  { value: "project_planning", label: "Project Planning" },
  { value: "risk_management", label: "Risk Management" },
  { value: "agile_methodologies", label: "Agile Methodologies" },
  { value: "time_management", label: "Time Management" },
  { value: "stakeholder_management", label: "Stakeholder Management" },
  { value: "problem_solving", label: "Problem Solving" },
  { value: "patience", label: "Patience" },
  { value: "product_knowledge", label: "Product Knowledge" },
  { value: "active_listening", label: "Active Listening" },
  { value: "technical_support", label: "Technical Support" },
  { value: "ux_design", label: "UX Design" },
  { value: "graphic_design", label: "Graphic Design" },
  { value: "prototyping", label: "Prototyping" },
  { value: "visual_communication", label: "Visual Communication" },
  { value: "typography", label: "Typography" },
  { value: "data_analysis", label: "Data Analysis" },
  { value: "machine_learning", label: "Machine Learning" },
  { value: "statistical_analysis", label: "Statistical Analysis" },
  { value: "python", label: "Python" },
  { value: "data_visualization", label: "Data Visualization" },
  { value: "content_writing", label: "Content Writing" },
  { value: "seo", label: "SEO" },
  { value: "social_media_management", label: "Social Media Management" },
  { value: "sales_strategies", label: "Sales Strategies" },
  { value: "email_marketing", label: "Email Marketing" },
  { value: "video_production", label: "Video Production" },
  { value: "cloud_computing", label: "Cloud Computing" },
  { value: "networking", label: "Networking" },
  { value: "cyber_security", label: "Cyber Security" },
  { value: "database_management", label: "Database Management" },
  { value: "user_research", label: "User Research" },
  { value: "public_speaking", label: "Public Speaking" },
  { value: "sales_forecasting", label: "Sales Forecasting" },
  { value: "lead_generation", label: "Lead Generation" },
  { value: "event_planning", label: "Event Planning" },
  { value: "html", label: "HTML" },
  { value: "next_js", label: "Next.JS" },
];
